apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-siyami-co-tls
spec:
  secretName: k8s-siyami-co
  issueRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: siyami.co
  dnsNames:
    - siyami.co
    - www.siyami.co
acme:
  config:
    - http01:
        ingressClass: nginx
      domains:
        - siyami.co
        - www.siyami.co

